name: gis
channels:
  - conda-forge
dependencies:
  - python=3.6   # or 2.7
  - flask
  # Install numpy (v 1.13.1)
  - numpy
  # Install pandas (v 0.20.3) --> bundled with python-dateutil (v 2.6.1) and pytz (v 2017.2)
  - pandas
  # Install scipy (v 0.19.1)
  - scipy
  # Install matplotlib (v 2.0.2) --> bundled with cycler, freetype, icu, jpeg, libpng, pyqt, qt, sip, sqlite, tornado, zlib
  - matplotlib
  # Install scikit-learn (v 0.19.0)
  - scikit-learn
  # Install networkx (v 1.11) --> bundled with decorator (v 4.1.2)
  - networkx
  # Install bokeh (v 0.12.9) --> bundled with jinja2, markupsafe, pyyaml, yaml -packages
  - bokeh
  # Install statsmodels (v 0.8.0) --> bundled with patsy (0.4.1)
  - statsmodels
  # Install PySpark (v 2.2.0) --> bundled with py4j (v 0.10.6)
  - pyspark
  # Install Geopandas (v 0.3.0) --> bundled with click, click-plugins, cligj, curl, descartes, expat, fiona, freexl, gdal, geos, hdf4, hdf5, kealib, krb5, libiconv, libnetcdf, libpq, libspatialindex, libspatialite, libtiff, libxml2, munch, openjpeg, pcre, proj4, psycopg2, pyproj, pysal, rtree, shapely, sqlalchemy, xerces-c
  - geopandas
  # Install cartopy (v 0.15.1) --> bundled with libxslt, lxml, olefile, owslib, pillow, pyepsg, pyshp
  - cartopy
  # Install osmnx (v 0.5.4) --> bundled with altair, bleach, branca, colorama, entrypoints, folium, geopy, html5lib, ipykernel, ipython, ipython_genutils, jedi, jsonschema, jupyter_client, jupyter_core, mistune, nbconvert, nbformat, notebook, pandoc, pandocfilters, pickleshare, prompt_toolkit, pygments, pyzmq, simplegeneric, testpath, traitlets, vega, vincent, wcwidth, webencodings
  - osmnx
  # Install Folium (v 0.5.0) --> bundled with altair, vega
  - folium
  - pip:
    - Flask-Testing
    # Install geoplot (v 0.0.4) using pip (on Linux: be sure to use pip that comes with conda distribution!) --> bundled with seaborn
    - geoplot
